
spring:
  application:
    name: eureka-zuul
    instance_id: eureka-zuul_001
  zipkin:
    base-url: http://localhost:9007
  sleuth:
    sampler:
      percentage: 1.0 
    
server:
  port: 9006
  servlet:
    context-path: /eureka-zuul
    
    
eureka:
  password: password
  client:
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-9001.com:9001/eureka-server/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    
zuul:
  routes:
    yypz:
      #strip-prefix: 为true请求path的值会调到url的值，例如请求http://localhost:9006/eureka-zuul/eureka-client/yypz/getHello
      #转发的路径会变为http://localhost:9003/getHello
      path: /eureka-client/**
      #通过指定url 
      #url: http://localhost:9003/eureka-client
      #通过eureka serviceId
      serviceId: HelloClient
      #不替换路径
      strip-prefix: false
  #是否开启重试功能
  retryable: false
      

ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  

logging:
  level:
    root: debug
