
spring:
  application:
    name: eureka-serviceProvider
    instance_id: eureka-serviceProvider_001
  zipkin:
    base-url: http://localhost:8007
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      label: master
      name: neo-config
      profile: dev
      uri: http://localhost:8008/configServer/
      
server:
  port: 8004
  servlet:
    context-path: /eureka-serviceProvider

eureka:
  password: password
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-8001.com:8001/eureka-server/eureka/,http://user:${eureka.password}@eureka-server-8002.com:8002/eureka-server/eureka/
  instance:
    #prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: ["health","info","refresh"]


endpoints:
  restart:
    enabled: true