
spring:
  application:
    name: eureka-serviceProvider
    instance_id: eureka-serviceProvider_002
  zipkin:
    base-url: http://localhost:9007
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      label: master
      name: yypz-config
      profile: dev
      uri: http://localhost:9008/configServer
      #discovery:  #支持集群
        #service-id:  
          
server:
  port: 9005
  servlet:
    context-path: /eureka-serviceProvider

eureka:
  password: password
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-9001.com:9001/eureka-server/eureka/,http://user:${eureka.password}@eureka-server-9002.com:9002/eureka-server/eureka/
  instance:
    #prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
 

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: ["health","info","refresh"]    
    
    
    
endpoints:
  restart:
    enabled: true