
spring:
  application:
    name: eureka-serviceProvider
    instance_id: eureka-serviceProvider_002
    
server:
  port: 8005
  servlet:
    context-path: /eureka-serviceProvider

eureka:
  password: password
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-8001.com:8001/eureka-server/eureka/,http://user:${eureka.password}@eureka-server-8002.com:8002/eureka-server/eureka/
  instance:
    #prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
 


endpoints:
  restart:
    enabled: true