
spring:
  application:
    name: ConfigServer
    instance_id: ConfigServer_001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YYPZ/YE_TEST    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password: 
    
   
server:
  port: 8008
  servlet:
    context-path: /configServer
