
spring:
  application:
    name: ZipkinServer
    instance_id: ZipkinServer_001
    
#http://localhost:9007/zipkin/    
server:
  port: 9007


eureka:
  password: password
  client:
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-9001.com:9001/eureka-server/eureka/,http://user:${eureka.password}@eureka-server-9002.com:9002/eureka-server/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10


management:
  metrics:
    web:
      server:
        auto-time-requests: false


endpoints:
  restart:
    enabled: true