
spring:
  application:
    #高可用部署时，每台的name必须相同才能互相发现可用
    name: eureka-server
    instance_id: eureka-server_002
    
server:
  port: 9002
  servlet:
    context-path: /eureka-server

eureka:
  password: password
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://user:${eureka.password}@eureka-server-9001.com:9001/eureka-server/eureka/
  instance:
    hostname: eureka-server-9002.com
    #prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
 


endpoints:
  restart:
    enabled: true